[package]
name = "test-rust-hyper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper="0.13.9"
tokio = { version = "0.2.22", features = ["full"] }

[profile.release]
lto = true